# config/sources.yml
# Fuentes para 8m-global-mapper

# config/sources.yml
seeds:
  "Europa":

    "Violencias_ES_Madrid":
      ciudad_default: "Madrid"
      pais_default: "España"
      urls:
        - https://hacialahuelgafeminista.org
        - https://movimientofeministamadrid.org
      hashtags: []
      social: []

    "Violencias_ES_Barcelona":
      ciudad_default: "Barcelona"
      pais_default: "España"
      urls:
        - https://assemblea8m.cat
        - https://feministes.cat
        - https://canodrom.barcelona/es
      hashtags: []
      social: []

    "Violencias_ES_multiciudad":
      ciudad_default: ""
      pais_default: "España"
      urls:
        - https://www.feministas.org
        - https://www.ccoo.es
        - https://www.cgt.es
        - https://sindicatodeestudiantes.net
        - https://www.feminicidio.net
      hashtags: []
      social: []

    "Violencias_FR":
      ciudad_default: "París"
      pais_default: "Francia"
      urls:
        - https://collectif-noustoutes.org
        - https://osezlefeminisme.fr
        - https://grevefeministe.fr
        - https://femmes-solidaires.org
      hashtags: []
      social: []

    "Violencias_UK":
      ciudad_default: "Londres"
      pais_default: "Reino Unido"
      urls:
        - https://feministfightback.org.uk
        - https://sistersuncut.org
        - https://womankind.org.uk
      hashtags: []
      social: []

    "Violencias_UK_Belfast":
      ciudad_default: "Belfast"
      pais_default: "Reino Unido"
      urls:
        - https://womensgrid.org.uk
      hashtags: []
      social: []

    "Violencias_PT":
      ciudad_default: "Lisboa"
      pais_default: "Portugal"
      urls:
        - https://umar.pt
        - https://plataformamulheres.org.pt
      hashtags: []
      social: []

    "Violencias_IT_Roma":
      ciudad_default: "Roma"
      pais_default: "Italia"
      urls:
        - https://nonunadimeno.wordpress.com
      hashtags: []
      social: []

    "Violencias_IT_Trieste":
      ciudad_default: "Trieste"
      pais_default: "Italia"
      urls:
        - https://nudmtrieste.noblogs.org
      hashtags: []
      social: []

    "Violencias_CH":
      ciudad_default: "Zürich"
      pais_default: "Suiza"
      urls:
        - https://frauenstreik.org
      hashtags: []
      social: []

    "Violencias_DE":
      ciudad_default: "Berlín"
      pais_default: "Alemania"
      urls:
        - https://www.frauen-gegen-gewalt.de
      hashtags: []
      social: []

    "Transfeminismos":
      ciudad_default: ""
      pais_default: ""
      urls: []
      hashtags: []
      social: []

    "Cuidados y trabajo":
      ciudad_default: ""
      pais_default: ""
      urls: []
      hashtags: []
      social: []

    "Antirracismo":
      ciudad_default: ""
      pais_default: ""
      urls: []
      hashtags: []
      social: []

    "Feminicidios / femicidios":
      ciudad_default: ""
      pais_default: ""
      urls: []
      hashtags: []
      social: []

    "LGBTIQ+":
      ciudad_default: ""
      pais_default: ""
      urls: []
      hashtags: []
      social: []

    "Indigenismo":
      ciudad_default: ""
      pais_default: ""
      urls: []
      hashtags: []
      social: []

    "Defensa territorial":
      ciudad_default: ""
      pais_default: ""
      urls: []
      hashtags: []
      social: []

  "Africa":

    "Violencias_ZA_Johannesburgo":
      ciudad_default: "Johannesburgo"
      pais_default: "Sudáfrica"
      urls:
        - https://genderlinks.org.za
      hashtags: []
      social: []

    "Violencias_ZA_CapeTown":
      ciudad_default: "Ciudad del Cabo"
      pais_default: "Sudáfrica"
      urls:
        - https://womensnet.org.za
      hashtags: []
      social: []

    "Violencias_NG":
      ciudad_default: "Lagos"
      pais_default: "Nigeria"
      urls:
        - https://wacol.org
      hashtags: []
      social: []

    "Violencias_AF_multiciudad":
      ciudad_default: ""
      pais_default: ""
      urls:
        - https://awdf.org
        - https://womin.africa
        - https://africanfeminism.com
        - https://feministafrica.net
        - https://baobabwomen.org
        - https://femnet.org
      hashtags: []
      social: []

    "Transfeminismos":
      ciudad_default: ""
      pais_default: ""
      urls: []
      hashtags: []
      social: []

    "Cuidados y trabajo":
      ciudad_default: ""
      pais_default: ""
      urls: []
      hashtags: []
      social: []

    "Antirracismo":
      ciudad_default: ""
      pais_default: ""
      urls: []
      hashtags: []
      social: []

    "Feminicidios / femicidios":
      ciudad_default: ""
      pais_default: ""
      urls: []
      hashtags: []
      social: []

    "LGBTIQ+":
      ciudad_default: ""
      pais_default: ""
      urls: []
      hashtags: []
      social: []

    "Indigenismo":
      ciudad_default: ""
      pais_default: ""
      urls: []
      hashtags: []
      social: []

    "Defensa territorial":
      ciudad_default: ""
      pais_default: ""
      urls: []
      hashtags: []
      social: []

  "America Norte":

    "Violencias_US":
      ciudad_default: ""
      pais_default: "Estados Unidos"
      urls:
        - https://www.womensmarch.com
        - https://feministfrequency.com
        - https://www.msmagazine.com
      hashtags: []
      social: []

    "Transfeminismos":
      ciudad_default: ""
      pais_default: ""
      urls: []
      hashtags: []
      social: []

    "Cuidados y trabajo":
      ciudad_default: ""
      pais_default: ""
      urls: []
      hashtags: []
      social: []

    "Antirracismo":
      ciudad_default: ""
      pais_default: ""
      urls: []
      hashtags: []
      social: []

    "Feminicidios / femicidios":
      ciudad_default: ""
      pais_default: ""
      urls: []
      hashtags: []
      social: []

    "LGBTIQ+":
      ciudad_default: ""
      pais_default: ""
      urls: []
      hashtags: []
      social: []

    "Indigenismo":
      ciudad_default: ""
      pais_default: ""
      urls: []
      hashtags: []
      social: []

    "Defensa territorial":
      ciudad_default: ""
      pais_default: ""
      urls: []
      hashtags: []
      social: []

  "America Centro":

    "Violencias_CR":
      ciudad_default: "San José"
      pais_default: "Costa Rica"
      urls:
        - https://cefemina.com
        - https://ccecr.org
      hashtags: []
      social: []

    "Violencias_SV":
      ciudad_default: "San Salvador"
      pais_default: "El Salvador"
      urls:
        - https://ormusa.org
        - https://ormusa.org/category/noticias
      hashtags: []
      social: []

    "Violencias_HN":
      ciudad_default: "Tegucigalpa"
      pais_default: "Honduras"
      urls:
        - https://derechosdelamujer.org
      hashtags: []
      social: []

    "Violencias_MX":
      ciudad_default: "Ciudad de México"
      pais_default: "México"
      urls:
        - https://gire.org.mx
        - https://asilegal.org.mx
      hashtags: []
      social: []

    "Transfeminismos":
      ciudad_default: ""
      pais_default: ""
      urls: []
      hashtags: []
      social: []

    "Cuidados y trabajo":
      ciudad_default: ""
      pais_default: ""
      urls: []
      hashtags: []
      social: []

    "Antirracismo":
      ciudad_default: ""
      pais_default: ""
      urls: []
      hashtags: []
      social: []

    "Feminicidios / femicidios":
      ciudad_default: ""
      pais_default: ""
      urls: []
      hashtags: []
      social: []

    "LGBTIQ+":
      ciudad_default: ""
      pais_default: ""
      urls: []
      hashtags: []
      social: []

    "Indigenismo":
      ciudad_default: ""
      pais_default: ""
      urls: []
      hashtags: []
      social: []

    "Defensa territorial":
      ciudad_default: ""
      pais_default: ""
      urls: []
      hashtags: []
      social: []

  "America Sur":

    "Violencias_AR":
      ciudad_default: "Buenos Aires"
      pais_default: "Argentina"
      urls:
        - https://www.niunamenos.ar/8m
        - https://feim.org.ar
        - https://www.agenciapresentes.org
      hashtags: []
      social: []

    "Violencias_CL":
      ciudad_default: "Santiago"
      pais_default: "Chile"
      urls:
        - https://cf8m.cl
      hashtags: []
      social: []

    "Violencias_BR_Brasilia":
      ciudad_default: "Brasilia"
      pais_default: "Brasil"
      urls:
        - https://marchadasmulheresnegras.com.br
        - https://cfemea.org.br
      hashtags: []
      social: []

    "Violencias_BR_SaoPaulo":
      ciudad_default: "São Paulo"
      pais_default: "Brasil"
      urls:
        - https://sof.org.br
        - https://articulacaodemulheres.org.br
      hashtags: []
      social: []

    "Violencias_PE":
      ciudad_default: "Lima"
      pais_default: "Perú"
      urls:
        - https://flora.org.pe
        - https://demuspe.org
      hashtags: []
      social: []

    "Violencias_BO":
      ciudad_default: "La Paz"
      pais_default: "Bolivia"
      urls:
        - https://coordinadoradelamujer.org.bo
        - https://mujerescreando.org
      hashtags: []
      social: []

    "Violencias_CO":
      ciudad_default: "Bogotá"
      pais_default: "Colombia"
      urls:
        - https://rednacionaldemujeres.org
        - https://humanas.org.co
      hashtags: []
      social: []

    "Transfeminismos":
      ciudad_default: ""
      pais_default: ""
      urls: []
      hashtags: []
      social: []

    "Cuidados y trabajo":
      ciudad_default: ""
      pais_default: ""
      urls: []
      hashtags: []
      social: []

    "Antirracismo":
      ciudad_default: ""
      pais_default: ""
      urls: []
      hashtags: []
      social: []

    "Feminicidios / femicidios":
      ciudad_default: ""
      pais_default: ""
      urls: []
      hashtags: []
      social: []

    "LGBTIQ+":
      ciudad_default: ""
      pais_default: ""
      urls: []
      hashtags: []
      social: []

    "Indigenismo":
      ciudad_default: ""
      pais_default: ""
      urls: []
      hashtags: []
      social: []

    "Defensa territorial":
      ciudad_default: ""
      pais_default: ""
      urls: []
      hashtags: []
      social: []

  "Asia":

    "Violencias_PH":
      ciudad_default: "Manila"
      pais_default: "Filipinas"
      urls:
        - https://gabriela.ph
      hashtags: []
      social: []

    "Violencias_IN":
      ciudad_default: "Nueva Delhi"
      pais_default: "India"
      urls:
        - https://feminisminindia.com
        - https://sangatsouthasia.org
      hashtags: []
      social: []

    "Transfeminismos":
      ciudad_default: ""
      pais_default: ""
      urls: []
      hashtags: []
      social: []

    "Cuidados y trabajo":
      ciudad_default: ""
      pais_default: ""
      urls: []
      hashtags: []
      social: []

    "Antirracismo":
      ciudad_default: ""
      pais_default: ""
      urls: []
      hashtags: []
      social: []

    "Feminicidios / femicidios":
      ciudad_default: ""
      pais_default: ""
      urls: []
      hashtags: []
      social: []

    "LGBTIQ+":
      ciudad_default: ""
      pais_default: ""
      urls: []
      hashtags: []
      social: []

    "Indigenismo":
      ciudad_default: ""
      pais_default: ""
      urls: []
      hashtags: []
      social: []

    "Defensa territorial":
      ciudad_default: ""
      pais_default: ""
      urls: []
      hashtags: []
      social: []

  "Oceania":

    "Violencias_AU_Adelaide":
      ciudad_default: "Adelaide"
      pais_default: "Australia"
      urls:
        - https://wwcsa.org.au
      hashtags: []
      social: []

    "Violencias_AU_Sydney":
      ciudad_default: "Sydney"
      pais_default: "Australia"
      urls:
        - https://ieu.asn.au
        - https://unwomen.org.au
      hashtags: []
      social: []

    "Violencias_AU_Canberra":
      ciudad_default: "Canberra"
      pais_default: "Australia"
      urls:
        - https://wel.org.au
      hashtags: []
      social: []

    "Violencias_NZ":
      ciudad_default: "Wellington"
      pais_default: "Nueva Zelanda"
      urls:
        - https://womensmarch.co.nz
        - https://ncwnz.org.nz
      hashtags: []
      social: []

    "Transfeminismos":
      ciudad_default: ""
      pais_default: ""
      urls: []
      hashtags: []
      social: []

    "Cuidados y trabajo":
      ciudad_default: ""
      pais_default: ""
      urls: []
      hashtags: []
      social: []

    "Antirracismo":
      ciudad_default: ""
      pais_default: ""
      urls: []
      hashtags: []
      social: []

    "Feminicidios / femicidios":
      ciudad_default: ""
      pais_default: ""
      urls: []
      hashtags: []
      social: []

    "LGBTIQ+":
      ciudad_default: ""
      pais_default: ""
      urls: []
      hashtags: []
      social: []

    "Indigenismo":
      ciudad_default: ""
      pais_default: ""
      urls: []
      hashtags: []
      social: []

    "Defensa territorial":
      ciudad_default: ""
      pais_default: ""
      urls: []
      hashtags: []
      social: []

priority_urls:
  - https://hacialahuelgafeminista.org
  - https://assemblea8m.cat
  - https://cf8m.cl
  - https://nonunadimeno.wordpress.com
  - https://marchadasmulheresnegras.com.br
  - https://collectif-noustoutes.org
  - https://feministfightback.org.uk
  - https://wwcsa.org.au
  - https://womensmarch.co.nz
  - https://gabriela.ph
  - https://ormusa.org/category/noticias
  - https://derechosdelamujer.org
  - https://ccecr.org
  - https://grevefeministe.fr
  - https://frauenstreik.org
  - https://movimientofeministamadrid.org
  - https://cefemina.com
  - https://flora.org.pe
  - https://coordinadoradelamujer.org.bo
  - https://rednacionaldemujeres.org
